version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
  backend:
    container_name: backend-nest
    build:
      context: ./backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
      - JWTKEY=${JWTKEY}
      - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
      - NODEMAILER_HOST=${NODEMAILER_HOST}
      - NODEMAILER_PORT=${NODEMAILER_PORT}
      - NODEMAILER_USER=${NODEMAILER_USER}
  frontend:
    container_name: frontend-react
    build:
      context: ./frontend
    depends_on:
      - db
      - backend
    restart: unless-stopped
    ports:
      - '8081:8081'