version: '3.9'

services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks: 
      - front
  db:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks: 
      - back
 
  backend:
    container_name: backend-nest
    build:
      context: ./backend
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=5432
      - TYPEORM_HOST=db
      - JWTKEY=${JWTKEY}
      - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
      - NODEMAILER_HOST=${NODEMAILER_HOST}
      - NODEMAILER_PORT=${NODEMAILER_PORT}
      - NODEMAILER_USER=${NODEMAILER_USER}
    networks: 
      - front
      - back
    ports:
      - 4000:4000

networks:
  front:
    driver: bridge
  back: 
    driver: bridge